"""init

Revision ID: 270cfe9e1573
Revises: 
Create Date: 2024-05-21 16:41:07.099434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270cfe9e1573'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('home_page', sa.String(), nullable=True),
    sa.Column('docs_url', sa.String(), nullable=True),
    sa.Column('package_url', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package'))
    )
    op.create_index(op.f('ix_package_author_email'), 'package', ['author_email'], unique=False)
    op.create_index(op.f('ix_package_create_at'), 'package', ['create_at'], unique=False)
    op.create_index(op.f('ix_package_update_at'), 'package', ['update_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_create_at'), 'user', ['create_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_login_at'), 'user', ['login_at'], unique=False)
    op.create_table('maintainer',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('maintainer', sa.String(), nullable=True),
    sa.Column('maintainer_email', sa.String(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('fk_maintainer_package_id_package'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintainer'))
    )
    op.create_table('release',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('major_ver', sa.BigInteger(), nullable=False),
    sa.Column('minor_ver', sa.BigInteger(), nullable=True),
    sa.Column('build_ver', sa.BigInteger(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name=op.f('fk_release_package_id_package'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release'))
    )
    op.create_index(op.f('ix_release_build_ver'), 'release', ['build_ver'], unique=False)
    op.create_index(op.f('ix_release_create_at'), 'release', ['create_at'], unique=False)
    op.create_index(op.f('ix_release_major_ver'), 'release', ['major_ver'], unique=False)
    op.create_index(op.f('ix_release_minor_ver'), 'release', ['minor_ver'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_minor_ver'), table_name='release')
    op.drop_index(op.f('ix_release_major_ver'), table_name='release')
    op.drop_index(op.f('ix_release_create_at'), table_name='release')
    op.drop_index(op.f('ix_release_build_ver'), table_name='release')
    op.drop_table('release')
    op.drop_table('maintainer')
    op.drop_index(op.f('ix_user_login_at'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_create_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_package_update_at'), table_name='package')
    op.drop_index(op.f('ix_package_create_at'), table_name='package')
    op.drop_index(op.f('ix_package_author_email'), table_name='package')
    op.drop_table('package')
    # ### end Alembic commands ###
